feat: test in expression mod.rs
OpenSRDK/symbolic-computation-rs pull request #7
Opened 2023-02-15 14:40 UTC by tibetsou

2023-02-17 03:27 UTC, KimuraYu45z requested changes

2023-02-17 03:27 UTC, KimuraYu45z commented on .vscode/settings.json
> +  "rust-analyzer.diagnostics.disabled": [
これの必要性はどっから？
おれなくても何も問題ないんやけどなにがあった

2023-02-17 03:27 UTC, KimuraYu45z commented on src/README.md
> +x diff
これは保存する必要はない
自分の手元で確認してくれれば十分

2023-02-17 03:27 UTC, KimuraYu45z commented on src/expression/mod.rs
> +        println!("c {:#?}", ec);
なにかしらassert eqたのむ
printlnだけのテストはあんまり

2023-02-17 03:27 UTC, KimuraYu45z commented on src/expression/operators/add.rs
> +        println!("c {:#?}", ec);
assert eq同様、昨日言ってたので。。

2023-02-21 05:23 UTC, KimuraYu45z commented on .vscode/settings.json
> +  "rust-analyzer.diagnostics.disabled": [
これ消してほしい

2023-02-21 05:23 UTC, KimuraYu45z commented on src/README.md
> +x diff
これもファイルごと消してほしい

2023-02-21 07:54 UTC, tibetsou commented on .vscode/settings.json
> +  "rust-analyzer.diagnostics.disabled": [
私のwindows環境下だとこれがないとエラーが出るんだよね...
rust analyzerのエラーだと思うんだけど
今はmacで作業してるからエラーは出てない

2023-02-21 07:56 UTC, tibetsou commented on .vscode/settings.json
> +  "rust-analyzer.diagnostics.disabled": [
いや、macでも同じエラー出たわ

2023-02-21 15:23 UTC, KimuraYu45z commented on .vscode/settings.json
> +  "rust-analyzer.diagnostics.disabled": [
なんのエラー？警告ではなく？

2023-02-22 13:09 UTC, tibetsou commented on .vscode/settings.json
> +  "rust-analyzer.diagnostics.disabled": [
下記の通りのエラー

エラー内容：[#derive] で"proc macro `〇〇` not expanded"という謎のエラーが出る
解決法：settings.jsonファイルに下記を追記
"rust-analyzer.diagnostics.disabled": [ "unresolved-proc-macro"],

2023-02-28 04:45 UTC, KimuraYu45z commented on .vscode/settings.json
> +  "rust-analyzer.diagnostics.disabled": [
https://www.reddit.com/r/rust/comments/vj2ghz/suddenly_proc_macro_main_not_expanded_proc_macro/
rust analyzerのバグらしいので自分のローカルにこのファイル忍ばせとくのは自由でコミットからは抜いてもらおうか

2023-03-01 13:44 UTC, KimuraYu45z approved these changes

2023-03-01 13:44 UTC, merged